### ISSUE TITLE
以npm导入包时候报错

### ISSUE THREAD

**Issue by zhoujingfu** [WindrunnerMax/FlowChartEditor#4]
npm导出包时报错
![image](https://github.com/WindrunnerMax/FlowChartEditor/assets/43539608/f5a7ffb6-576b-45d5-8e3b-2d28c8503e47)
请问是项目还有要做哪些配置吗？项目是vite

**Comment by WindRunnerMax** [comment]
可以起个demo复现我看一下

**Comment by zhoujingfu** [comment]
> 可以起个demo复现我看一下
感觉是vite的问题  请查看：https://stackblitz.com/edit/vitejs-vite-vcy6ab

**Comment by WindRunnerMax** [comment]
试了下确实应该是vite的问题，我发现打包cjs模块会有一个this，这个this正常应该是window然而在模块内成了void

**Comment by zhoujingfu** [comment]
> 试了下确实应该是vite的问题，我发现打包cjs模块会有一个this，这个this正常应该是window然而在模块内成了void

又啥解决吧办法吗 ^_^

**Comment by WindRunnerMax** [comment]
周末我抽空看下

**Comment by WindRunnerMax** [comment]
用0.0.14版本吧，也要注意引用包里的CSS

**Comment by zhoujingfu** [comment]
好的谢谢，编辑器可以正常打开，但还是有些问题
![image](https://github.com/WindrunnerMax/FlowChartEditor/assets/43539608/7822f7f8-9898-472e-bedc-0eb372a1cc74)

**Comment by WindRunnerMax** [comment]
window上挂上这两个变量，设置为null就行，关闭时再销毁，这应该是mxgraph的问题，但是这个包也不再维护了

**Comment by WindRunnerMax** [comment]
> 好的谢谢，编辑器可以正常打开，但还是有些问题 ![image](https://user-images.githubusercontent.com/43539608/246705345-7822f7f8-9898-472e-bedc-0eb372a1cc74.png)

这两个问题已经在`0.0.15`版本修复
