### ISSUE TITLE
这些图形数据是怎么来的，本地运行起来没有

### ISSUE THREAD

**Issue by qyh613** [WindrunnerMax/FlowChartEditor#5]
![20231227112636](https://github.com/WindrunnerMax/FlowChartEditor/assets/67140048/acb3b0ca-f2b3-4bf6-a349-74b71b681d52)

**Comment by WindRunnerMax** [comment]
<img width="350" alt="image" src="https://github.com/WindrunnerMax/FlowChartEditor/assets/33169019/abd73f6f-0c9d-4af4-a141-c00fca24854c">

你打开的这是完整的drawio吧，这个需要你自己二开
